### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by Daniel-W-Innes** [omarimran2000/Elevator-Simulator#5]
* figure out some form of dependency management
* setup Junit5
* add test cases

**Comment by BraxtonMartin0** [comment]
Added csv read test and elevator motor test (isn't needed for this iteration)

**Comment by Daniel-W-Innes** [comment]
Please don't close tickets until you merge your code. This could be easily accomplished with [Closes](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). Unless you are closing this issue because it Is not needed for this milestone in which case I apologize for reopening it.
